defaults:
  - _self_
  - model: SAMobileNet


base_path: 
  __target__: pathlib.Path
  pathsegments: /workspace/data/ready_data/info
dataset_name: 'small' #['small', 'medium', 'large','unconfident']
train_manifest_path: ${base_path} / 'crowd_${dataset_name}.jsonl'
val_manifest_path: ${base_path} / 'test' / 'crowd_test.jsonl'

train_params:
  batch_size: 128
  epoch_count: 1
  learning_rate: 1.e-3
  optimizer_step: 5
  optimizer_gamma: 1
  weight_decay: 1.e-6
  clip_grad: False


pt_model_path:
collate_fn:
  __target__: core.dataset.adaptive_padding_collate_fn
augm_func:
  __target__: core.dataset.get_augm_func
  time_mask_param: 40
  freq_mask_param: 16
  crop_augm_max_cut_size: 40

get_train_weights: 

DUMP_BEST_CHECKPOINTS: True
DUMP_LAST_CHECKPOINTS: True
BEST_CHECKPOINTS_WARMUP: 5

