defaults:
  - _self_
  - model: SAMobileNet
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

base_path: ./data/info

wavs_folder: test_data
features_folder: ${wavs_folder}
dataset_name: 'medium' #['small', 'medium', 'large','unconfident']
train_manifest_path: ${base_path}/crowd_${dataset_name}.jsonl
val_manifest_path: ${base_path}/test/crowd_test.jsonl

batch_size: 32

best_model_folder: model_weights

train_params:
  num_epochs: 25
  learning_rate: 3.e-4
  optimizer_step: 7
  optimizer_gamma: 0.8
  weight_decay: 1.e-6
  clip_grad: False


threshold: 0.9

pt_model_path:
get_train_weights: 

collate_fn:
  _target_: core.dataset.adaptive_padding_collate_fn

augm_func:
  _target_: core.dataset.get_augm_func
  time_mask_param: 40
  freq_mask_param: 16
  crop_augm_max_cut_size: 40

hydra:  
  output_subdir: null  
  run:  
    dir: .