defaults:
  - _self_
  - model: SAMobileNet
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

base_path: /workspace/data/info

dataset_name: 'small' #['small', 'medium', 'large','unconfident']
train_manifest_path: ${base_path}/crowd_${dataset_name}.jsonl
val_manifest_path: ${base_path}/test/crowd_test.jsonl

batch_size: 32

best_model_folder: 'best_model'

train_params:
  num_epochs: 7
  learning_rate: 1.e-3
  optimizer_step: 5
  optimizer_gamma: 2
  weight_decay: 0
  clip_grad: False


pt_model_path:
get_train_weights: 

collate_fn:
  _target_: core.dataset.adaptive_padding_collate_fn

augm_func:
  _target_: core.dataset.get_augm_func
  time_mask_param: 40
  freq_mask_param: 16
  crop_augm_max_cut_size: 40

hydra:  
  output_subdir: null  
  run:  
    dir: .